services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    expose:
      - 9090
    networks:
      - kingdoms-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning
      - ./metrics/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${BASE_URL}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`kingdoms-game.ru`) && PathPrefix(`/grafana`)
      - traefik.http.routers.grafana.tls.certresolver=myresolver
      - traefik.http.routers.grafana.entrypoints=external
      - traefik.http.routers.grafana.priority=200
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    expose:
      - 3000
    networks:
      - kingdoms-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  kingdoms-network:
    external: true
