global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets: ["kingdoms-traefik:8080"]
  - job_name: "rooms"
    static_configs:
      - targets:
          - "kingdoms-kingdoms-rooms-1:7400"
          - "kingdoms-kingdoms-rooms-2:7400"
          - "kingdoms-kingdoms-rooms-3:7400"
          - "kingdoms-kingdoms-rooms-4:7400"
