{
 "title": "Rooms",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Среднее число захваченных территорий",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(player_territory_size_total_sum[1m]) / rate(player_territory_size_total_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средний размер сообщения по типам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ws_message_size_bytes_sum[1m]) / rate(ws_message_size_bytes_count[1m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Среднее число ходов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(game_duration_turns_total_sum[1m]) / rate(game_duration_turns_total_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by(message_type) (ws_message_size_bytes_sum / ws_message_size_bytes_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время операция игрового цикла",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "legendFormat": "__auto" },
    {
     "expr": "sum by (operation) (rate(game_turn_duration_seconds_sum[30s])) / \nsum by (operation) (rate(game_turn_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}