"""Update models

Revision ID: 51f0306fa3e9
Revises: 172c7a717cb7
Create Date: 2025-01-09 07:04:50.299404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f0306fa3e9'
down_revision: Union[str, None] = '172c7a717cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_profile_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_profile_id_fkey', 'user', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    # ### end Alembic commands ###
