"""update

Revision ID: 9769db21c596
Revises: 8a791a70ef38
Create Date: 2025-01-17 13:49:51.860434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9769db21c596'
down_revision: Union[str, None] = '8a791a70ef38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_user_id', table_name='profile')
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.drop_column('user', 'last_login_dt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.create_index('ix_profile_user_id', 'profile', ['user_id'], unique=False)
    # ### end Alembic commands ###
